export goal1=~/Desktop/GOAL-20130711/goal
export goal2=~/Desktop/GOAL-20140808/goal
export goal3=~/Desktop/GOAL-20141016/goal
export goal4=~/Desktop/GOAL-20141017/goal
export goal5=~/Desktop/GOAL-20141017_installed/goal

